worlds:
  world:
    spawn:
      timer: 100
      reward: 500
      activator:
        x: 1
        y: 1
        z: 1
      p1:
        x: 0
        y: 0
        z: 0
      p2:
        x: 2
        y: 2
        z: 2
