worlds:
  world:
    default:
      timer: 40
      reward: 2
      activators:
        - - -5
          - -58
          - -21
      p1:
        x: -11
        y: -59
        z: -28
      p2:
        y: -53
        z: -12
        x: 2

