name: MayhemSpawn
version: '1.0-SNAPSHOT'
main: org.forg.mayhemspawn.integration.MayhemPlugin
api-version: '1.20'
depend: [WorldEdit, Vault, CommandAPI]
#commands:
#  mspawn:
#    permission-message: Нет прав
#    usage:
#      - mspawn tool
#      - mspawn create <имя> <таймер>
#    description:
#      - mspawn tool
#      - mspawn create <имя> <таймер>
#    permission: mayhemspawn.*
#  mspawn tool:
#    permission-message: Нет прав
#    description: Выдать селектор
#    permission: mayhemspawn.tool
#  mspawn activate <имя>:
#    permission-message: Нет прав
#    description: Начать арену
#    permission: mayhemspawn.activate
#    aliases:
#      - mspawn start
#  mspawn create <имя> <таймер>:
#    permission-message: Нет прав
#    description: Создать арену
#    permission: mayhemspawn.*
#    usage: mspawn create <имя> <таймер>